[package]
name = "gpu_filters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pollster = "0.3.0"
image = "0.24.6"
bytemuck = "1.13.1"

[dependencies.wgpu]
path = "/home/builder/source/wgpu/wgpu"
